In [3]:
 
from sqlalchemy import create_engine
def get_engine():
        return create_engine(
            f"postgresql+psycopg2://shikhabordia:readonly@localhost:5432/postgres",
            echo=False  # good for debugging
        )
import pandas as pd
sql_query = 'SELECT * FROM court'


df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   court_id  canton_id court_string
0         1          1       AI_BZG
1         2          1        AI_KG

In [126]:
tables = ['court', 'canton', 'chamber','court_name', 'canton_name',  'language', 'judgment', 'judgment_map', 'citation','citation_type','file','section', 'section_type',
 'num_tokens','decision','file_number','party', 'party_type', 'person', 'judicial_person_type', 'judicial_person',
 'spider','file', 'lower_court']

sql_query = 'SELECT * FROM court'

sql_query = 'SELECT * FROM chamber'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'
#sql_query = 'SELECT * FROM judgment'

for table in tables:
    #print(table)
    sql_query = 'SELECT * FROM '+ table
    df_iterator = pd.read_sql(sql_query,get_engine().connect())
    print(table, len(df_iterator))

court 3
canton 2
chamber 3
court_name 15
canton_name 10
language 5
judgment 7
judgment_map 0
citation 0
citation_type 3
file 4382
section 0
section_type 6
num_tokens 0
decision 56
file_number 56
party 0
party_type 4
person 0
judicial_person_type 3
judicial_person 0
spider 2
file 4382
lower_court 0

In [128]:
sql_query = 'SELECT * FROM court'
sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM lower_court'
#sql_query = 'SELECT * FROM citation_type'
#sql_query = 'SELECT * FROM judgment'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

,file_number_id,decision_id,text
0,1,1b78dd88-db6e-5f13-919c-5a7f520ed227,§ 10 GBAG; Zusammenrechnung von Kauf- und Werk...
1,2,e094e413-fc3d-5b27-a0b4-dba7817ae0e8,§ 11 GBAG; Wert der Gesamteigentumsanteile
2,3,eefb73b4-653d-5d04-9c0f-33735728a869,§ 10 GBAG; Zusammenrechnung von Kauf- und Werk...
3,4,f4721254-da4b-55e6-859a-07415e0bccfb,§ 10 GBAG; Zusammenrechnung von Kauf- und Werk...
4,5,0af55218-a657-5d2a-8343-51a43e891efa,§ 10 GBAG; Zusammenrechnung von Kauf- und Werk...
5,6,06d17bcf-ea14-5054-b75f-1c70dccd9089,§ 8 und 22 GBAG; Umstrukturierung
6,7,a592c302-e8d0-5200-9c2c-98285cc2018c,AGVE 2004 S. 489 Nr. 127
7,8,ca6d8dcb-b1a0-5606-a20c-f54a876c3018,AGVE 2002 S. 643 Nr. 147
8,9,460ac296-1533-539d-8755-6ab31b130655,AGVE 2001 S. 563 Nr. 122
9,10,252a036f-d1c6-5d95-8f48-14893223111a,K 2-2021
10,11,218e0ec7-613d-5c67-bb94-a7dc85c9b33a,KSE 4-2020
11,12,b809953a-97ba-554b-8376-751193864c76,KE 12-2022
12,13,d75d6741-d163-536e-a121-7b835a9c9081,V 17-2020
13,14,3acda794-f8e9-5d1c-ad3d-eb5dfe38e848,V 16-2019
14,15,f9e0bedc-bbdb-5f1c-a2de-8831f900378c,V 12-2019
15,16,ab3c6e0b-dddc-59af-a001-26e025b38f0d,V 4-2022
16,17,23517264-d182-5712-b674-41fefbda277e,V 1-2021
17,18,938763c7-fde3-593f-af86-7a9c0457d817,K 3-2021
18,19,2ed174c5-44b3-5785-9424-b30b2e0f4130,V 11-2019
19,20,c1385003-1b69-5f02-bf66-8cbabfa85bac,V 4-2023
20,21,b98fc496-2b55-54e4-90fb-3d1bf29bd122,V 7-2020
21,22,39e86c2d-33b3-52a3-955e-c86128154cfc,V 9-2020
22,23,e0e4e232-cca8-5f28-82d5-d560486914e9,K 3-2020
23,24,6959b410-944d-5959-bcc5-e096e6f79ff4,V 8-2021
24,25,95a3bbeb-cbc4-5141-8101-b6a83d7304ec,V 7-2021
25,26,c70cc871-8bae-5dd2-a03c-8cb9e6b407cb,V 14-2019
26,27,84c01026-12cf-53a7-b86b-0c7fb463a6c2,V 14-2023
27,28,5aa5396b-11ec-5f14-ab31-086bcfa0dcab,V 17-2023
28,29,84e131b4-5785-5a56-81c6-2952669b65e1,K 5-2019
29,30,6d06b9cb-35d4-51ae-a8f7-99bf0b4525b5,V 18-2023
30,31,33f35d52-6661-51ec-93b0-5cf3bfe97c6b,V 18-2021
31,32,176fe62e-bdf9-55ea-9461-8bbe086e81bb,V 1-2024
32,33,c503f3a2-b4e0-50de-a736-a7e1101e4f63,K 7-2019
33,34,bb421dfc-278f-56dd-8c9a-746de278f72f,K 1-2018
34,35,2ca7c95e-ec0b-5006-9e69-2ad6897f956e,KE 15-2023
35,36,75ef850d-bfda-50fb-bb37-58a8255d2737,K 7-2021
36,37,501ba750-6224-5e7d-acf0-d23eccaa1183,V 7-2023
37,38,04d6c9d4-cbe8-537d-aaba-b57627eab96c,V 2-2021
38,39,ab1c5c78-532c-5088-8c0f-061294afb860,V 4-2023
39,40,ba97f8e3-88b2-5267-8a93-c5e82a9bfa5c,K 8-2019
40,41,82193b53-876a-5399-9a91-fa0884c9138d,K 5-2020
41,42,e614f401-7f1e-5959-8069-5842ef5f8bb6,V 8-2023
42,43,be79fb8a-3d2f-5bfe-804b-24611d599ba7,V 13-2021
43,44,3ba01430-a383-5e10-ba55-356c67433678,K 1-2020
44,45,69187421-f1e0-57df-af6b-8eb36ca509b6,KE 33-2023
45,46,023b7721-36c6-50ac-9121-b5958d06d1e1,V 3-2020
46,47,95f0f780-e5b3-5613-a63d-5cf06af2976c,V 10-2023
47,48,ebb6fd22-f123-50d9-ab94-e0d66175c530,KE 15-2023
48,49,c4250640-4bbf-55a5-b6b2-fd965c99f697,V 11-2020
49,50,4fe77c4f-b75e-5797-9a4a-e05386890a35,V 6-2020
50,51,e4c7c99e-2796-525a-adf5-96437e40634c,V 12-2020
51,52,067c67de-744e-5a3b-9577-a2d2537e2a20,V 6-2021
52,53,e21089c9-475e-5133-aa65-8b0944c7929a,K 2-2020
53,54,bbdaac6f-bf9e-5127-8881-8be8951ad84f,V 15-2021
54,55,0084424a-25a3-5063-a30c-4bd1b3cf44dc,V 1-2022
55,56,f279cf6b-6134-56f2-83b7-0fd194cd5129,KE 3-2022

In [7]:
sql_query = 'SELECT * FROM chamber'# WHERE court_id = 3'#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   chamber_id  court_id  spider_id chamber_string
0           1         1          1     AI_BZG_001
1           2         2          1      AI_KG_001

In [8]:
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

   chamber_id  court_id  spider_id chamber_string
0           1         1          1     AI_BZG_001
1           2         2          1      AI_KG_001

In [17]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" '#AG_AK_001 '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "CH_ED*" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*"
                                                     ^

[SQL: SELECT * FROM chamber WHERE chamber_id  like "CH_ED*" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [4]:
sql_query = 'SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" '#CH_ED_001" '

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "AG_AK_001" does not exist
LINE 1: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001"
                                                 ^

[SQL: SELECT * FROM chamber WHERE chamber_id = "AG_AK_001" ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [25]:
sql_query = 'SELECT * FROM court'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator)

172

In [26]:
df_iterator

     court_id  canton_id court_string
0           1          2        AG_AK
1           2          2       AG_AUK
2           3          2        AG_GB
3           4          2        AG_JL
4           5          2        AG_OG
..        ...        ...          ...
167       168         27       ZH_SRK
168       169         27       ZH_SVG
169       170         27       ZH_UPL
170       171         27        ZH_VG
171       172         27        ZH_XX

[172 rows x 3 columns]

In [21]:
sql_query = 'SELECT * FROM judicial_person'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [decision_id, person_id, judicial_person_type_id, is_president]
Index: []

In [93]:
sql_query = 'SELECT * FROM decision'
df_iterator1 = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator1)
df_list[0]
len(df_iterator1), len(df_list[0])

df_iterator1

,decision_id,language_id,chamber_id,file_id,date,topic
0,03b1c203-0f26-5ea0-bad0-51dae9f743bc,1,380,7925,1996-07-22,
1,4ec76444-f120-5b97-93e6-0420cfcb0e4d,1,380,7926,2016-01-11,
2,295105e8-155d-56fe-804d-1c6e37a7ff99,1,380,7927,2015-12-04,
3,0f3521c0-5123-5be5-b68a-b250a55ec052,1,380,7928,2014-04-08,
4,a91f0eca-0bec-5be9-833f-e4aa49560170,1,380,7929,2016-12-05,
...,...,...,...,...,...,...
190852,cebf1aab-b51c-565c-915b-7cdca5e8700d,1,294,206385,2015-11-17,
190853,97ef6e1a-54e1-5179-bd34-e86816da8773,1,294,206386,2010-05-04,
190854,30b3d6d2-8250-5b3f-8055-2b3fe7eb4520,1,292,206387,2021-05-27,
190855,dc9d314a-6d06-5923-996b-19bfe043d311,1,292,206388,2019-12-17,
190856,c94f7ff9-1f1c-5b88-a957-f539161a4c0f,1,294,206389,2011-04-12,

In [94]:
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

In [59]:
sql_query = 'SELECT * FROM decision'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

,decision_id,language_id,chamber_id,file_id,date,topic
0,03b1c203-0f26-5ea0-bad0-51dae9f743bc,1,380,7925,1996-07-22,
1,4ec76444-f120-5b97-93e6-0420cfcb0e4d,1,380,7926,2016-01-11,
2,295105e8-155d-56fe-804d-1c6e37a7ff99,1,380,7927,2015-12-04,
3,0f3521c0-5123-5be5-b68a-b250a55ec052,1,380,7928,2014-04-08,
4,a91f0eca-0bec-5be9-833f-e4aa49560170,1,380,7929,2016-12-05,
...,...,...,...,...,...,...
190852,cebf1aab-b51c-565c-915b-7cdca5e8700d,1,294,206385,2015-11-17,
190853,97ef6e1a-54e1-5179-bd34-e86816da8773,1,294,206386,2010-05-04,
190854,30b3d6d2-8250-5b3f-8055-2b3fe7eb4520,1,292,206387,2021-05-27,
190855,dc9d314a-6d06-5923-996b-19bfe043d311,1,292,206388,2019-12-17,
190856,c94f7ff9-1f1c-5b88-a957-f539161a4c0f,1,294,206389,2011-04-12,

In [3]:
import pandas as pd
sql_query = 'SELECT * FROM chamber'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

# chamber_df = df_iterator
# chamber_df[chamber_df['chamber_string']=="AG_OG_%"]
# chamber_df[chamber_df['chamber_string'].str.contains("AG_OG")]
#len(chamber_df),

NameError: name 'get_engine' is not defined

In [81]:
import os
folders = "data/spiders/"
chamber_set = set()
for folder in os.listdir(folders):
    #print(folders+folder)
   
    files = os.listdir(folders+folder)
    #print(len(files))
    files = ['_'.join([ x for x in f.split('_')[:3]]) for f in files]
    file_set = set(files)
    #print(len(file_set))
    chamber_set.update(file_set)

print(len(chamber_set))
chamber_set

20

{'AG_GB_001',
 'AG_HG_002',
 'AG_JG_001',
 'AG_OGA_001',
 'AG_OGA_002',
 'AG_OGA_003',
 'AG_OGA_004',
 'AG_OGA_005',
 'AG_OGA_006',
 'AG_OGA_999',
 'AG_OG_003',
 'AG_OG_004',
 'AG_OG_010',
 'AG_OG_012',
 'AG_OG_014',
 'AG_OG_999',
 'AG_VG_002',
 'AG_VSG_002',
 'AI_BZG_001',
 'AI_KG_001'}

In [80]:
files

['AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_BZG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001',
 'AI_KG_001']

In [92]:
list(chamber_set)[:5]

['BS_SVG_00', 'CH_VB_021', 'GE_CJ_013', 'TI_GIAR_0', 'VD_SR_001']

In [88]:
ch_set = set(list(chamber_df['chamber_string']))
len(ch_set)

424

In [91]:
print(len(ch_set - chamber_set), len(chamber_set-ch_set))
ch_set - chamber_set, chamber_set-ch_set

183 102

({'AG_AUK_001',
  'AG_JL_001',
  'AG_RR_001',
  'AG_SVWG_001',
  'AG_SVWG_002',
  'AG_SVWG_999',
  'AG_UPL_001',
  'AG_VB_003',
  'AG_VB_999',
  'AG_XX_001',
  'AI_BZG_001',
  'AI_UPL_001',
  'AR_KG_002',
  'AR_KG_003',
  'AR_OG_999',
  'AR_RR_001',
  'AR_SRK_001',
  'AR_UPL_001',
  'AR_VB_001',
  'AR_XX_001',
  'BE_NAB_001',
  'BE_NAB_002',
  'BE_NAB_003',
  'BE_NAB_999',
  'BE_SRK_001',
  'BE_UPL_001',
  'BE_VB_999',
  'BE_XX_001',
  'BL_UPL_001',
  'BL_XX_001',
  'BL_ZMG_001',
  'BS_APG_001',
  'BS_SVG_001',
  'BS_UPL_001',
  'BS_XX_001',
  'CH_BGE_001',
  'CH_BGE_002',
  'CH_BGE_003',
  'CH_BGE_004',
  'CH_BGE_005',
  'CH_BGE_006',
  'CH_BGE_007',
  'CH_BGE_008',
  'CH_BGE_009',
  'CH_BGE_010',
  'CH_BGE_011',
  'CH_BGE_999',
  'CH_BGer_001',
  'CH_BGer_002',
  'CH_BGer_004',
  'CH_BGer_005',
  'CH_BGer_006',
  'CH_BGer_008',
  'CH_BGer_009',
  'CH_BGer_010',
  'CH_BGer_012',
  'CH_BGer_013',
  'CH_BGer_014',
  'CH_BGer_015',
  'CH_BGer_016',
  'CH_BGer_999',
  'CH_BSTG_001',
  'CH_BVGE_001',
  'CH_EDÖB_001',
  'CH_EDÖB_002',
  'CH_EDÖB_003',
  'CH_EDÖB_004',
  'CH_EDÖB_999',
  'CH_PATG_001',
  'CH_UPL_001',
  'CH_WBK_001',
  'CH_XX_001',
  'FR_TAMA_001',
  'FR_UPL_001',
  'FR_XX_001',
  'GE_CAPJ_001',
  'GE_CJ_999',
  'GE_TAPI_001',
  'GE_UPL_001',
  'GE_XX_001',
  'GL_KG_999',
  'GL_UPL_001',
  'GL_XX_999',
  'GR_KG_012',
  'GR_UPL_001',
  'GR_VG_999',
  'GR_XX_001',
  'JU_TPI_006',
  'JU_TPI_007',
  'JU_TPI_999',
  'JU_UPL_001',
  'JU_XX_001',
  'LU_AUK_001',
  'LU_BKD_001',
  'LU_BZG_001',
  'LU_GSD_001',
  'LU_JSD_001',
  'LU_KG_005',
  'LU_RSH_001',
  'LU_UPL_001',
  'LU_XX_001',
  'NE_ARA_001',
  'NE_ASL_001',
  'NE_ASS_001',
  'NE_ATS_001',
  'NE_TR_999',
  'NE_UPL_001',
  'NE_XX_001',
  'NW_UPL_001',
  'NW_XX_001',
  'OW_UPL_001',
  'OW_XX_001',
  'SG_ABSK_001',
  'SG_KGN_001',
  'SG_KGN_999',
  'SG_UPL_001',
  'SG_VB_002',
  'SG_VB_999',
  'SG_VGN_001',
  'SG_VSG_001',
  'SG_VWEK_001',
  'SG_XX_001',
  'SH_UPL_001',
  'SH_XX_001',
  'SO_STG_001',
  'SO_UPL_001',
  'SO_VSG_001',
  'SO_XX_001',
  'SZ_UPL_001',
  'SZ_XX_001',
  'TG_UPL_001',
  'TG_XX_001',
  'TI_CARP_001',
  'TI_CATI_001',
  'TI_CRP_001',
  'TI_GIAR_001',
  'TI_GPC_001',
  'TI_TCAS_001',
  'TI_TCA_001',
  'TI_TPC_001',
  'TI_TRAC_001',
  'TI_TRAC_002',
  'TI_TRAC_003',
  'TI_TRAC_004',
  'TI_TRAC_005',
  'TI_TRAC_006',
  'TI_TRAC_007',
  'TI_TRAC_999',
  'TI_TRAP_001',
  'TI_TRAP_002',
  'TI_TRAP_999',
  'TI_TRPI_001',
  'TI_UPL_001',
  'TI_XX_999',
  'UR_UPL_001',
  'UR_XX_001',
  'VD_TPHA_001',
  'VD_UPL_001',
  'VD_XX_001',
  'VS_AG_001',
  'VS_BZG_001',
  'VS_BZG_002',
  'VS_BZG_003',
  'VS_BZG_004',
  'VS_BZG_005',
  'VS_BZG_006',
  'VS_BZG_007',
  'VS_BZG_008',
  'VS_BZG_009',
  'VS_BZG_999',
  'VS_SRK_001',
  'VS_UPL_001',
  'VS_XX_001',
  'ZG_UPL_001',
  'ZG_VG_999',
  'ZG_XX_001',
  'ZH_BRK_001',
  'ZH_KSG_001',
  'ZH_SOBE_001',
  'ZH_SRK_001',
  'ZH_SVG_001',
  'ZH_UPL_001',
  'ZH_XX_001'},
 {'AG_AUK_00',
  'AG_HG_001',
  'AG_HG_002',
  'AG_JG_001',
  'AG_LWRK_0',
  'AG_OGA_00',
  'AG_OGA_99',
  'AG_OG_003',
  'AG_OG_004',
  'AG_OG_010',
  'AG_OG_011',
  'AG_OG_012',
  'AG_OG_013',
  'AG_OG_014',
  'AG_OG_998',
  'AG_OSB_00',
  'AG_PRG_00',
  'AG_RGAR_0',
  'AG_SKBG_0',
  'AG_SRG_00',
  'AG_SVWG_0',
  'AG_UPL_00',
  'AG_VG_001',
  'AG_VG_002',
  'AG_VSG_00',
  'AI_BZG_00',
  'AR_UPL_00',
  'BE_NAB_00',
  'BE_SRK_00',
  'BE_UPL_00',
  'BL_ZMG_00',
  'BS_APG_00',
  'BS_SVG_00',
  'CH_BGE_00',
  'CH_BGer_0',
  'CH_BGer_9',
  'CH_BSTG_0',
  'CH_BVGE_0',
  'CH_EDÖB_0',
  'CH_EDÖB_9',
  'CH_PATG_0',
  'CH_UPL_00',
  'CH_WBK_00',
  'FR_UPL_00',
  'GE_CAPJ_0',
  'GE_TAPI_0',
  'JU_TPI_00',
  'LU_AUK_00',
  'LU_BKD_00',
  'LU_BZG_00',
  'LU_GSD_00',
  'LU_JSD_00',
  'LU_UPL_00',
  'NE_ARA_00',
  'NE_ASL_00',
  'NE_ASS_00',
  'NE_ATS_00',
  'OW_UPL_00',
  'SG_ABSK_0',
  'SG_KGN_00',
  'SG_KGN_99',
  'SG_OG_002',
  'SG_OG_003',
  'SG_OG_004',
  'SG_OG_005',
  'SG_OG_006',
  'SG_VGN_00',
  'SG_VSG_00',
  'SG_VWEK_0',
  'SH_UPL_00',
  'SO_STG_00',
  'SO_VSG_00',
  'TG_UPL_00',
  'TI_CARP_0',
  'TI_CATI_0',
  'TI_CRP_00',
  'TI_GIAR_0',
  'TI_TCAS_0',
  'TI_TCA_00',
  'TI_TPC_00',
  'TI_TRAC_0',
  'TI_TRAP_0',
  'TI_TRPI_0',
  'UR_AKBR_0',
  'UR_AKBR_9',
  'UR_REB_00',
  'VD_TPHA_0',
  'VD_UPL_00',
  'VS_AG_999',
  'VS_BZG_00',
  'VS_BZG_99',
  'VS_SRK_00',
  'VS_UPL_00',
  'XX_UPL_00',
  'ZG_UPL_00',
  'ZH_BRK_00',
  'ZH_KSG_00',
  'ZH_OG_006',
  'ZH_SOBE_0',
  'ZH_SRK_00',
  'ZH_SVG_00',
  'ZH_UPL_00'})

In [5]:
sql_query = 'SELECT * FROM court'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])

df_iterator

# chamber_df = df_iterator
# chamber_df[chamber_df['chamber_string']=="AG_OG_%"]
# chamber_df[chamber_df['chamber_string'].str.contains("AG_OG")]
#len(chamber_df),

Empty DataFrame
Columns: [court_id, canton_id, court_string]
Index: []

In [30]:
sql_query = 'SELECT * FROM language'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])
df_iterator

   language_id iso_code
0            1       de
1            2       fr
2            3       it
3            4       en
4            5       nn

In [70]:
spider_dict_list = process_map(self.build_spider_dict, json_filenames, chunksize=self.chunksize)

NameError: name 'process_map' is not defined

In [ ]:
corresponding_pdf_path = Path(json_file).with_suffix('.pdf')
corresponding_html_path = Path(json_file).with_suffix('.html')

In [ ]:
court_dict_template = {key: '' for key in self.court_keys}

In [95]:
sql_query = 'SELECT * FROM decision'
sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
df_list[0]
len(df_iterator), len(df_list[0])
len(df_iterator)

1254

In [ ]:
self.update(self.get_engine(self.db_scrc), df, 'decision',   ['language_id'], self.output_dir, None, 'decision_id')

In [ ]:
sql_query = 'SELECT * FROM language'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)

len(df_list[0])
df_list[0]

   language_id iso_code
0            1       de
1            2       fr
2            3       it
3            4       en
4            5       na

In [88]:
sql_query = 'SELECT * FROM chamber'
sql_query = 'SELECT * FROM canton'
sql_query = 'SELECT * FROM court'
sql_query = 'SELECT * FROM canton_name'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM file'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)

df_list[0]

   canton_id  language_id                          name
0          1            1                        Aargau
1          2            1         Appenzell Innerrhoden
2          1            2                       Argovie
3          2            2  Appenzell Rhodes-Intérieures
4          1            3                       Argovia
5          2            3            Appenzello Interno
6          1            4                        Aargau
7          2            4         Appenzell Innerrhoden

In [96]:
# with get_engine().connect() as connection:
#     #df['file_id'] = pd.read_sql(query, engine.connect())["file_id"][0]
#     df= pd.read_sql(sql_query,connection)
#     connection.close()

In [71]:
sql_query = 'SELECT * FROM language'
sql_query = 'SELECT * FROM file'
sql_query = 'SELECT * FROM decision'
sql_query = 'SELECT * FROM citation'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [citation_id, citation_type_id, decision_id, url, text]
Index: []

In [115]:
sql_query = 'SELECT * FROM language'
sql_query = 'SELECT * FROM file'
#sql_query = 'SELECT * FROM decision'
#sql_query = 'SELECT * FROM citation'
#sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
df_iterator = pd.read_sql(sql_query,get_engine().connect())

df_list = list(df_iterator)
len(df_iterator)
df_iterator

,file_id,file_name,html_url,pdf_url,html_raw,pdf_raw
0,1,AG_OG_003_7c2e339cd83f1bbdccff_2017-04-03,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,"Entscheid des Obergerichts, 5. Zivilkammer, vo..."
1,2,AG_OGA_002_3d49d5dce342c99dfee6_2020-01-31,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
2,3,AG_OGA_002_-Handelsrecht-Bauhan_2020-06-20,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
3,4,AG_OGA_006_04b32d27a49d8880a3c3_2014-06-10,,https://www.ag.ch/media/kanton-aargau/jb/dokum...,,AGVE-2006\n\n\n§ 65a Abs. 4 EG ZGB \nDer Bunde...
4,5,AG_OG_012_-Handelsrecht-Bauhan_2020-01-31,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
...,...,...,...,...,...,...
1287,1286,AG_OG_012_-Handelsrecht-Zivilp_2019-06-06,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Urteil/Entscheid\n\n\n Handelsgericht \n\n2. K...
1288,1287,AG_OGA_999_-Kindes--und-Erwachs_2014-04-03,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,AGVE-2006\n\n\nArt. 363 Abs. 2 Ziff. 3 ZGB \n...
1289,1288,AG_OGA_999_30fe0e8e7d5880fc42f6_2002-12-11,,https://www.ag.ch/media/kanton_aargau/dvi/doku...,,Microsoft Word - VGE vom 11.12.2002.doc\n\n\n ...
1290,1289,AG_HG_002_-Handelsrecht-Bauhan_2019-10-07,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,Handelsgericht \n\n2. Kammer \n\n \n\n \n\nHSU...
1291,1290,AG_OG_004_56e0a91075a0155223b3_2013-10-18,,https://www.ag.ch/media/kanton_aargau/jb/dokum...,,AGVE-2006\n\n\n Weigert sich die Vormundschaft...

In [100]:
import pandas as pd

df = pd.DataFrame(columns=['Name', 'Age', 'City'])

print(df)

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [116]:
sql_query = 'SELECT * FROM language'
sql_query = 'SELECT * FROM court'
#sql_query = 'SELECT * FROM decision'
sql_query = 'SELECT * FROM citation'
sql_query = 'SELECT * FROM judicial_person_type'
#sql_query = 'SELECT * FROM party_type'
#sql_query = 'SELECT * FROM file_number'
#sql_query = 'SELECT * FROM spider'
sql_query = 'SELECT * FROM judgment'
sql_query = 'SELECT * FROM person'

df_iterator = pd.read_sql(sql_query,get_engine().connect(), chunksize=1000)

df_list = list(df_iterator)
df_list[0]

Empty DataFrame
Columns: [person_id, name, is_natural_person, gender]
Index: []